# Generated by Django 2.1.1 on 2018-09-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrengoods',
            options={'verbose_name': '子栏目', 'verbose_name_plural': '子栏目'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '父栏目', 'verbose_name_plural': '父栏目'},
        ),
    ]
